/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Disco.Disco;
import Disco.Particion;

/**
 *
 * @author josep
 */
public class FrmDisco extends javax.swing.JFrame {
    Disco c;
    /**
     * Creates new form Principal
     */
    public FrmDisco() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        lblEstasEn = new javax.swing.JLabel();
        btnCrearDisco = new javax.swing.JButton();
        btnCrearParticion = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        btnAtras.setText("ATRÁS");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, -1, -1));

        lblEstasEn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        lblEstasEn.setForeground(new java.awt.Color(255, 255, 255));
        lblEstasEn.setText("ESTÁS EN: CONFIGURACIÓN DEL DISCO");
        getContentPane().add(lblEstasEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        btnCrearDisco.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btnCrearDisco.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearDisco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/discoCrear32.png"))); // NOI18N
        btnCrearDisco.setText("CREAR");
        btnCrearDisco.setToolTipText("Crear disco");
        btnCrearDisco.setContentAreaFilled(false);
        btnCrearDisco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCrearDisco.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/discoCrear32.png"))); // NOI18N
        btnCrearDisco.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/discoCrear48.png"))); // NOI18N
        btnCrearDisco.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCrearDisco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCrearDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearDiscoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, 80));

        btnCrearParticion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btnCrearParticion.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearParticion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/discoParticion32.png"))); // NOI18N
        btnCrearParticion.setText("PARTICIONES");
        btnCrearParticion.setToolTipText("Crear particiones");
        btnCrearParticion.setContentAreaFilled(false);
        btnCrearParticion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCrearParticion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/discoParticion32.png"))); // NOI18N
        btnCrearParticion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/discoParticion48.png"))); // NOI18N
        btnCrearParticion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCrearParticion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCrearParticion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearParticionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearParticion, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, 80));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearParticionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearParticionActionPerformed
        Particion p1= new Particion(200,c);
    }//GEN-LAST:event_btnCrearParticionActionPerformed

    private void btnCrearDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDiscoActionPerformed
        c = Disco.getInstancia();
        c.crearDisco();
    }//GEN-LAST:event_btnCrearDiscoActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDisco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDisco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDisco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDisco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDisco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCrearDisco;
    private javax.swing.JButton btnCrearParticion;
    private javax.swing.JLabel lblEstasEn;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
