/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Disco.Disco;
import javax.swing.JOptionPane;

/**
 *
 * @author josep
 */
public class FrmPrincipal extends javax.swing.JFrame {
    Disco d;

    
    /**
     * Creates new form Principal
     */
    public FrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        jpbDisco.setValue(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTamannio = new javax.swing.JLabel();
        lblQueMadre = new javax.swing.JLabel();
        btnDisco = new javax.swing.JButton();
        jpbDisco = new javax.swing.JProgressBar();
        lblDisco = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTamannio.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        lblTamannio.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblTamannio, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 40, 20));

        lblQueMadre.setText("jLabel1");
        getContentPane().add(lblQueMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 580, -1, -1));

        btnDisco.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btnDisco.setForeground(new java.awt.Color(255, 255, 255));
        btnDisco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disco32.png"))); // NOI18N
        btnDisco.setText("DISCO");
        btnDisco.setToolTipText("Configurar disco");
        btnDisco.setContentAreaFilled(false);
        btnDisco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDisco.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disco32.png"))); // NOI18N
        btnDisco.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disco48.png"))); // NOI18N
        btnDisco.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnDisco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 362, -1, 80));

        jpbDisco.setMinimum(1);
        jpbDisco.setValue(0);
        getContentPane().add(jpbDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 600, 20));

        lblDisco.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        lblDisco.setForeground(new java.awt.Color(255, 255, 255));
        lblDisco.setText("ESPACIO DEL DISCO");
        getContentPane().add(lblDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, 20));

        btnModificar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar32.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setToolTipText("Modificar archivo");
        btnModificar.setContentAreaFilled(false);
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar32.png"))); // NOI18N
        btnModificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar48.png"))); // NOI18N
        btnModificar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, 80));

        btnCrear.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crear32.png"))); // NOI18N
        btnCrear.setText("CREAR");
        btnCrear.setToolTipText("Crear archivo");
        btnCrear.setContentAreaFilled(false);
        btnCrear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCrear.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crear32.png"))); // NOI18N
        btnCrear.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crear48.png"))); // NOI18N
        btnCrear.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCrear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, 80));

        btnEliminar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar32.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setToolTipText("Eliminar archivo");
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar32.png"))); // NOI18N
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar48.png"))); // NOI18N
        btnEliminar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, -1, 80));

        btnVer.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btnVer.setForeground(new java.awt.Color(255, 255, 255));
        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver32.png"))); // NOI18N
        btnVer.setText("VER");
        btnVer.setToolTipText("Ver archivos");
        btnVer.setContentAreaFilled(false);
        btnVer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVer.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver32.png"))); // NOI18N
        btnVer.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver48.png"))); // NOI18N
        btnVer.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnVer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        getContentPane().add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, 80));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        FrmEliminar eliminar = new FrmEliminar();
        eliminar.setVisible(true);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        if (Disco.verificar()) {
            JOptionPane.showMessageDialog(null, "Debe crear un disco para crear archivos o carpetas", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            FrmCrear crear = new FrmCrear();
            crear.setVisible(true);
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (Disco.verificar()) {
            JOptionPane.showMessageDialog(null, "Debe crear un modificar para crear archivos o carpetas", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            FrmModificar modificar = new FrmModificar();
            modificar.setVisible(true);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        FrmVer ver = new FrmVer();
        ver.setVisible(true);
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscoActionPerformed
        FrmDisco disco = new FrmDisco();
        disco.setVisible(true);
    }//GEN-LAST:event_btnDiscoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnDisco;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVer;
    public static javax.swing.JProgressBar jpbDisco;
    private javax.swing.JLabel lblDisco;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblQueMadre;
    public static javax.swing.JLabel lblTamannio;
    // End of variables declaration//GEN-END:variables
}
